#!/bin/bash
set -eo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

source ${SCRIPT_DIR}/lib/network-mirror.sh
source ${SCRIPT_DIR}/lib/agent-script.sh "PRE_PLAN"

echo "Executing pre-plan hook... Complete"