#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

source ${SCRIPT_DIR}/lib/network-mirror.sh
source ${SCRIPT_DIR}/lib/agent-script.sh "PRE_APPLY"

echo "Executing pre-apply hook... Complete"